import { CookbookModel } from './types'
import { mergeCatalog } from './ollama-catalog'
import { OLLAMA_LIBRARY_CATALOG } from './model-catalog.generated'

export const CURATED_MODEL_CATALOG: CookbookModel[] = [
  // Llama 3.2 family
  {
    id: 'llama3.2:1b-q4',
    name: 'Llama 3.2 1B (Q4_K_M)',
    family: 'llama',
    parameterBillions: 1.2,
    sizeTier: 'tiny',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code'],
    ramRequiredGB: 1.5,
    ramRecommendedGB: 2.0,
    diskSizeGB: 1.3,
    ollamaTag: 'llama3.2:1b',
    ggufUrl: 'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf',
    ggufFilename: 'Llama-3.2-1B-Instruct-Q4_K_M.gguf',
    ggufFileSize: 808000000,
    description: 'Ultra-lightweight Llama 3.2 model optimized for edge devices and low-memory setups.',
    highlights: ['Extremely fast', 'Low memory footprint', 'Great for simple tasks']
  },
  {
    id: 'llama3.2:3b-q4',
    name: 'Llama 3.2 3B (Q4_K_M)',
    family: 'llama',
    parameterBillions: 3.2,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'creative'],
    ramRequiredGB: 2.8,
    ramRecommendedGB: 4.0,
    diskSizeGB: 2.0,
    ollamaTag: 'llama3.2',
    ggufUrl: 'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf',
    ggufFilename: 'Llama-3.2-3B-Instruct-Q4_K_M.gguf',
    ggufFileSize: 2020000000,
    description: 'The standard lightweight model from Meta. Outstanding balance of speed and capability.',
    highlights: ['Fast responses', 'Highly capable reasoning', 'Fits on almost any modern laptop']
  },
  {
    id: 'llama3.2:3b-q8',
    name: 'Llama 3.2 3B (Q8_0)',
    family: 'llama',
    parameterBillions: 3.2,
    sizeTier: 'small',
    quantization: 'Q8_0',
    useCases: ['chat', 'code', 'creative'],
    ramRequiredGB: 4.5,
    ramRecommendedGB: 6.0,
    diskSizeGB: 3.4,
    ollamaTag: 'llama3.2:3b-instruct-q8_0',
    ggufUrl: 'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q8_0.gguf',
    ggufFilename: 'Llama-3.2-3B-Instruct-Q8_0.gguf',
    ggufFileSize: 3400000000,
    description: 'High-precision 8-bit quantization of Llama 3.2 3B. Reduced quantization loss for sharper reasoning.',
    highlights: ['Better output quality', 'Slightly higher memory required', 'Good fallback for 8GB RAM systems']
  },
  // Llama 3.1 / 3.3
  {
    id: 'llama3.1:8b-q4',
    name: 'Llama 3.1 8B (Q4_K_M)',
    family: 'llama',
    parameterBillions: 8.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'creative', 'reasoning'],
    ramRequiredGB: 5.5,
    ramRecommendedGB: 8.0,
    diskSizeGB: 4.7,
    ollamaTag: 'llama3.1',
    ggufUrl: 'https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
    ggufFilename: 'Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
    ggufFileSize: 4920000000,
    description: 'Meta\'s popular 8B model. Highly versatile, handles complex logic and coding well.',
    highlights: ['Strong coding support', '128k context window', 'Very popular general-purpose model']
  },
  {
    id: 'hermes-3-llama-3.1:8b-q4',
    name: 'Hermes 3 8B (Q4_K_M)',
    family: 'hermes',
    parameterBillions: 8.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'creative', 'agentic'],
    ramRequiredGB: 5.5,
    ramRecommendedGB: 8.0,
    diskSizeGB: 4.9,
    ollamaTag: 'hermes3:8b',
    ggufUrl: 'https://huggingface.co/bartowski/Hermes-3-Llama-3.1-8B-GGUF/resolve/main/Hermes-3-Llama-3.1-8B-Q4_K_M.gguf',
    ggufFilename: 'Hermes-3-Llama-3.1-8B-Q4_K_M.gguf',
    ggufFileSize: 4920000000,
    description: 'NousResearch\'s highly capable and uncensored fine-tune of Llama 3.1 8B. Excellent for general chat, roleplay, and agentic workflows.',
    highlights: ['Uncensored', 'Agentic system prompts', 'Superb instruction following']
  },
  {
    id: 'llama3.3:70b-q4',
    name: 'Llama 3.3 70B (Q4_K_M)',
    family: 'llama',
    parameterBillions: 70.0,
    sizeTier: 'xl',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning', 'creative'],
    ramRequiredGB: 43.0,
    ramRecommendedGB: 48.0,
    diskSizeGB: 42.0,
    ollamaTag: 'llama3.3',
    ggufUrl: 'https://huggingface.co/bartowski/Llama-3.3-70B-Instruct-GGUF/resolve/main/Llama-3.3-70B-Instruct-Q4_K_M.gguf',
    ggufFilename: 'Llama-3.3-70B-Instruct-Q4_K_M.gguf',
    ggufFileSize: 42500000000,
    description: 'State-of-the-art 70B model from Meta. Performs on par with much larger closed-source models.',
    highlights: ['Superb reasoning', 'Excellent for complex coding tasks', 'Requires high-end GPU/Unified Memory']
  },
  // DeepSeek R1 Reasoning Family
  {
    id: 'deepseek-r1:1.5b-q4',
    name: 'DeepSeek R1 1.5B (Q4_K_M)',
    family: 'deepseek',
    parameterBillions: 1.5,
    sizeTier: 'tiny',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 1.8,
    ramRecommendedGB: 3.0,
    diskSizeGB: 1.1,
    ollamaTag: 'deepseek-r1:1.5b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-1.5B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf',
    ggufFileSize: 1120000000,
    description: 'DeepSeek\'s ultra-lightweight reasoning model. Outputs chain-of-thought `<think>` tags.',
    highlights: ['Native chain-of-thought reasoning', 'Runs on low-end hardware', 'Impressive math and logic for size']
  },
  {
    id: 'deepseek-r1:7b-q4',
    name: 'DeepSeek R1 7B (Q4_K_M)',
    family: 'deepseek',
    parameterBillions: 7.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 5.0,
    ramRecommendedGB: 8.0,
    diskSizeGB: 4.7,
    ollamaTag: 'deepseek-r1:7b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf',
    ggufFileSize: 4680000000,
    description: 'DeepSeek\'s distilled 7B model. Strikingly strong reasoning, math, and coding abilities.',
    highlights: ['Best value-to-performance reasoning', 'Detailed step-by-step thinking', 'Great for 8GB/16GB RAM machines']
  },
  {
    id: 'deepseek-r1:8b-q4',
    name: 'DeepSeek R1 8B (Llama-based)',
    family: 'deepseek',
    parameterBillions: 8.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 5.5,
    ramRecommendedGB: 8.0,
    diskSizeGB: 4.7,
    ollamaTag: 'deepseek-r1:8b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Llama-8B-GGUF/resolve/main/DeepSeek-R1-Distill-Llama-8B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Llama-8B-Q4_K_M.gguf',
    ggufFileSize: 4920000000,
    description: 'DeepSeek\'s reasoning model distilled into the Llama 3.1 8B architecture.',
    highlights: ['Llama-based fine-tune', 'Excellent logical consistency', 'Runs well on 16GB unified memory']
  },
  {
    id: 'deepseek-r1:14b-q4',
    name: 'DeepSeek R1 14B (Q4_K_M)',
    family: 'deepseek',
    parameterBillions: 14.0,
    sizeTier: 'medium',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 9.5,
    ramRecommendedGB: 16.0,
    diskSizeGB: 9.0,
    ollamaTag: 'deepseek-r1:14b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-14B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf',
    ggufFileSize: 9000000000,
    description: 'DeepSeek\'s distilled 14B Qwen-based model. Excellent for intermediate complex problem-solving.',
    highlights: ['Strong developer companion', 'Highly detailed explanations', 'Needs 16GB+ RAM']
  },
  {
    id: 'deepseek-r1:32b-q4',
    name: 'DeepSeek R1 32B (Q4_K_M)',
    family: 'deepseek',
    parameterBillions: 32.0,
    sizeTier: 'large',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 20.0,
    ramRecommendedGB: 24.0,
    diskSizeGB: 20.0,
    ollamaTag: 'deepseek-r1:32b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-32B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf',
    ggufFileSize: 20000000000,
    description: 'Distilled 32B reasoning model. Near frontier-level math and coding capabilities.',
    highlights: ['Frontier-like math/coding', 'Deep logical synthesis', 'Requires 24GB-32GB RAM/VRAM']
  },
  {
    id: 'deepseek-r1:70b-q4',
    name: 'DeepSeek R1 70B (Q4_K_M)',
    family: 'deepseek',
    parameterBillions: 70.0,
    sizeTier: 'xl',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 43.0,
    ramRecommendedGB: 48.0,
    diskSizeGB: 42.0,
    ollamaTag: 'deepseek-r1:70b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Llama-70B-GGUF/resolve/main/DeepSeek-R1-Distill-Llama-70B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Llama-70B-Q4_K_M.gguf',
    ggufFileSize: 42500000000,
    description: 'DeepSeek R1 distilled into Llama 70B. Superb reasoning capacity matching top closed models.',
    highlights: ['Exceptional performance', 'Full complex analysis', 'Requires high-end Mac Studio or multi-GPU PC']
  },
  // Qwen Family
  {
    id: 'qwen2.5:0.5b-q4',
    name: 'Qwen 2.5 0.5B (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 0.5,
    sizeTier: 'tiny',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'embedding'],
    ramRequiredGB: 0.8,
    ramRecommendedGB: 1.2,
    diskSizeGB: 0.4,
    ollamaTag: 'qwen2.5:0.5b',
    description: 'Super-tiny model by Alibaba, suitable for very low resource microcontrollers and servers.',
    highlights: ['Lightning fast', 'Extremely low memory', 'Excellent multilingual base']
  },
  {
    id: 'qwen2.5-coder:14b-q4',
    name: 'Qwen 2.5 Coder 14B (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 14.0,
    sizeTier: 'medium',
    quantization: 'Q4_K_M',
    useCases: ['code', 'reasoning'],
    ramRequiredGB: 9.5,
    ramRecommendedGB: 16.0,
    diskSizeGB: 9.0,
    ollamaTag: 'qwen2.5-coder:14b',
    description: 'Alibaba\'s mid-sized coding model. Perfect balance between speed and advanced code design.',
    highlights: ['Complex software architecture design', 'Wide language coverage', 'Needs 16GB+ RAM']
  },
  {
    id: 'qwen2.5:32b-q4',
    name: 'Qwen 2.5 32B (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 32.0,
    sizeTier: 'large',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning', 'creative'],
    ramRequiredGB: 20.0,
    ramRecommendedGB: 24.0,
    diskSizeGB: 19.0,
    ollamaTag: 'qwen2.5:32b',
    description: 'Large-scale Qwen model. Excellent reasoning, instruction following, and multilingual coding.',
    highlights: ['Superb multi-step logic', 'Accurate translations', 'Needs 24GB-32GB system memory']
  },
  {
    id: 'glm-4.7-flash:q4',
    name: 'GLM-4.7 Flash (Q4_K_M)',
    family: 'glm',
    parameterBillions: 9.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['agentic', 'reasoning', 'code', 'chat'],
    ramRequiredGB: 6.5,
    ramRecommendedGB: 8.0,
    diskSizeGB: 5.8,
    ollamaTag: 'glm-4.7-flash',
    description: 'Agentic reasoning version of GLM-4. Built for step-by-step thinking and tool-calling execution.',
    highlights: ['Native chain-of-thought thinking', 'Optimized tool calling', 'Agentic workflow specialist']
  },
  // Gemma 3 & 4 Family (Google)
  {
    id: 'gemma3:1b-q4',
    name: 'Gemma 3 1B (Q4_K_M)',
    family: 'gemma',
    parameterBillions: 1.0,
    sizeTier: 'tiny',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'creative'],
    ramRequiredGB: 1.2,
    ramRecommendedGB: 2.0,
    diskSizeGB: 0.9,
    ollamaTag: 'gemma3:1b',
    description: 'Google\'s compact 3rd gen Gemma. Multilingual support across 140+ languages.',
    highlights: ['Ultra-fast inference', '140+ languages', 'Runs on low-spec edge hardware']
  },
  {
    id: 'gemma3:4b-q4',
    name: 'Gemma 3 4B (Q4_K_M)',
    family: 'gemma',
    parameterBillions: 4.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'vision'],
    ramRequiredGB: 3.2,
    ramRecommendedGB: 4.5,
    diskSizeGB: 2.6,
    ollamaTag: 'gemma3:4b',
    description: 'Lightweight multimodal Gemma 3 model. Exceptional vision and text capabilities.',
    highlights: ['Native image input', '128k context', 'Low RAM footprint']
  },
  {
    id: 'gemma3:12b-q4',
    name: 'Gemma 3 12B (Q4_K_M)',
    family: 'gemma',
    parameterBillions: 12.0,
    sizeTier: 'medium',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning', 'vision'],
    ramRequiredGB: 8.0,
    ramRecommendedGB: 12.0,
    diskSizeGB: 7.3,
    ollamaTag: 'gemma3:12b',
    description: 'Google\'s mid-size Gemma 3. High benchmark performance matching larger 20B+ models.',
    highlights: ['Multimodal vision & text', '128k context window', 'Frontier-grade reasoning']
  },
  {
    id: 'gemma4:12b-q4',
    name: 'Gemma 4 12B (Q4_K_M)',
    family: 'gemma',
    parameterBillions: 12.0,
    sizeTier: 'medium',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning', 'agentic', 'vision'],
    ramRequiredGB: 8.5,
    ramRecommendedGB: 12.0,
    diskSizeGB: 7.6,
    ollamaTag: 'gemma4:12b',
    description: 'Google Gemma 4 flagship mid-sized model. 256k context, native audio/video/image understanding.',
    highlights: ['Native audio/video/text multimodal', '256k context', 'Apache 2.0 licensed']
  },
  {
    id: 'gemma4:26b-q4',
    name: 'Gemma 4 26B MoE (Q4_K_M)',
    family: 'gemma',
    parameterBillions: 26.0,
    sizeTier: 'large',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning', 'agentic'],
    ramRequiredGB: 17.5,
    ramRecommendedGB: 24.0,
    diskSizeGB: 15.5,
    ollamaTag: 'gemma4:26b',
    description: 'Mixture of Experts Gemma 4 model with 4B active parameters per token.',
    highlights: ['Fast MoE inference', 'Frontier-level code & logic', 'Needs 24GB unified memory']
  },
  // Qwen 3 Family (Alibaba)
  {
    id: 'qwen3:1.7b-q4',
    name: 'Qwen 3 1.7B (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 1.7,
    sizeTier: 'tiny',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code'],
    ramRequiredGB: 1.5,
    ramRecommendedGB: 2.5,
    diskSizeGB: 1.2,
    ollamaTag: 'qwen3:1.7b',
    description: 'Ultra-efficient Qwen 3 entry. Strong multilingual performance for small devices.',
    highlights: ['Native thinking mode', 'Low memory demand', 'Multilingual specialist']
  },
  {
    id: 'qwen3:8b-q4',
    name: 'Qwen 3 8B (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 8.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning', 'agentic'],
    ramRequiredGB: 5.5,
    ramRecommendedGB: 8.0,
    diskSizeGB: 4.9,
    ollamaTag: 'qwen3:8b',
    description: 'Alibaba\'s Qwen 3 8B model with integrated chain-of-thought reasoning mode.',
    highlights: ['Chain-of-thought thinking', '256k context', 'Excellent 8GB RAM option']
  },
  {
    id: 'qwen3:30b-q4',
    name: 'Qwen 3 30B MoE (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 30.0,
    sizeTier: 'large',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning', 'agentic'],
    ramRequiredGB: 19.0,
    ramRecommendedGB: 24.0,
    diskSizeGB: 18.0,
    ollamaTag: 'qwen3:30b',
    description: 'Qwen 3 Mixture of Experts model (3B active parameters). Near-instant response speeds.',
    highlights: ['MoE speedup (3B active)', '256k context', 'Top-tier coding benchmark performance']
  },
  {
    id: 'qwen3-coder:30b-q4',
    name: 'Qwen 3 Coder 30B (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 30.0,
    sizeTier: 'large',
    quantization: 'Q4_K_M',
    useCases: ['code', 'agentic', 'reasoning'],
    ramRequiredGB: 19.0,
    ramRecommendedGB: 24.0,
    diskSizeGB: 18.2,
    ollamaTag: 'qwen3-coder:30b',
    description: 'Specialized agentic coding model from Alibaba. Built for SWE-bench workflows.',
    highlights: ['SWE-Bench open-weight leader', '256k context', 'Deep architectural coding design']
  },
  // Falcon 3 Family (TII)
  {
    id: 'falcon3:3b-q4',
    name: 'Falcon 3 3B (Q4_K_M)',
    family: 'falcon',
    parameterBillions: 3.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code'],
    ramRequiredGB: 2.5,
    ramRecommendedGB: 4.0,
    diskSizeGB: 2.0,
    ollamaTag: 'falcon3:3b',
    description: 'TII\'s lightweight Falcon 3 model. Optimized for low latency inference.',
    highlights: ['Fast generation speed', 'Low system overhead', 'Great background assistant']
  },
  {
    id: 'falcon3:10b-q4',
    name: 'Falcon 3 10B (Q4_K_M)',
    family: 'falcon',
    parameterBillions: 10.0,
    sizeTier: 'medium',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning'],
    ramRequiredGB: 7.0,
    ramRecommendedGB: 10.0,
    diskSizeGB: 6.2,
    ollamaTag: 'falcon3:10b',
    description: 'Mid-size Falcon 3 model. Strong balance of efficiency and reasoning.',
    highlights: ['Solid logical reasoning', 'Efficient memory usage', 'Runs well on 16GB RAM']
  }
]

export const MODEL_CATALOG: CookbookModel[] = mergeCatalog(
  CURATED_MODEL_CATALOG,
  OLLAMA_LIBRARY_CATALOG
)

