import { CookbookModel } from './types'

export const MODEL_CATALOG: CookbookModel[] = [
  // Llama 3.2 family
  {
    id: 'llama3.2:1b-q4',
    name: 'Llama 3.2 1B (Q4_K_M)',
    family: 'llama',
    parameterBillions: 1.2,
    sizeTier: 'tiny',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code'],
    ramRequiredGB: 1.5,
    ramRecommendedGB: 2.0,
    diskSizeGB: 1.3,
    ollamaTag: 'llama3.2:1b',
    ggufUrl: 'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf',
    ggufFilename: 'Llama-3.2-1B-Instruct-Q4_K_M.gguf',
    ggufFileSize: 808000000,
    description: 'Ultra-lightweight Llama 3.2 model optimized for edge devices and low-memory setups.',
    highlights: ['Extremely fast', 'Low memory footprint', 'Great for simple tasks']
  },
  {
    id: 'llama3.2:3b-q4',
    name: 'Llama 3.2 3B (Q4_K_M)',
    family: 'llama',
    parameterBillions: 3.2,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'creative'],
    ramRequiredGB: 2.8,
    ramRecommendedGB: 4.0,
    diskSizeGB: 2.0,
    ollamaTag: 'llama3.2',
    ggufUrl: 'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf',
    ggufFilename: 'Llama-3.2-3B-Instruct-Q4_K_M.gguf',
    ggufFileSize: 2020000000,
    description: 'The standard lightweight model from Meta. Outstanding balance of speed and capability.',
    highlights: ['Fast responses', 'Highly capable reasoning', 'Fits on almost any modern laptop']
  },
  {
    id: 'llama3.2:3b-q8',
    name: 'Llama 3.2 3B (Q8_0)',
    family: 'llama',
    parameterBillions: 3.2,
    sizeTier: 'small',
    quantization: 'Q8_0',
    useCases: ['chat', 'code', 'creative'],
    ramRequiredGB: 4.5,
    ramRecommendedGB: 6.0,
    diskSizeGB: 3.4,
    ollamaTag: 'llama3.2:3b-instruct-q8_0',
    ggufUrl: 'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q8_0.gguf',
    ggufFilename: 'Llama-3.2-3B-Instruct-Q8_0.gguf',
    ggufFileSize: 3400000000,
    description: 'High-precision 8-bit quantization of Llama 3.2 3B. Reduced quantization loss for sharper reasoning.',
    highlights: ['Better output quality', 'Slightly higher memory required', 'Good fallback for 8GB RAM systems']
  },
  // Llama 3.1 / 3.3
  {
    id: 'llama3.1:8b-q4',
    name: 'Llama 3.1 8B (Q4_K_M)',
    family: 'llama',
    parameterBillions: 8.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'creative', 'reasoning'],
    ramRequiredGB: 5.5,
    ramRecommendedGB: 8.0,
    diskSizeGB: 4.7,
    ollamaTag: 'llama3.1',
    ggufUrl: 'https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
    ggufFilename: 'Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
    ggufFileSize: 4920000000,
    description: 'Meta\'s popular 8B model. Highly versatile, handles complex logic and coding well.',
    highlights: ['Strong coding support', '128k context window', 'Very popular general-purpose model']
  },
  {
    id: 'llama3.3:70b-q4',
    name: 'Llama 3.3 70B (Q4_K_M)',
    family: 'llama',
    parameterBillions: 70.0,
    sizeTier: 'xl',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning', 'creative'],
    ramRequiredGB: 43.0,
    ramRecommendedGB: 48.0,
    diskSizeGB: 42.0,
    ollamaTag: 'llama3.3',
    ggufUrl: 'https://huggingface.co/bartowski/Llama-3.3-70B-Instruct-GGUF/resolve/main/Llama-3.3-70B-Instruct-Q4_K_M.gguf',
    ggufFilename: 'Llama-3.3-70B-Instruct-Q4_K_M.gguf',
    ggufFileSize: 42500000000,
    description: 'State-of-the-art 70B model from Meta. Performs on par with much larger closed-source models.',
    highlights: ['Superb reasoning', 'Excellent for complex coding tasks', 'Requires high-end GPU/Unified Memory']
  },

  // DeepSeek R1 Reasoning Family
  {
    id: 'deepseek-r1:1.5b-q4',
    name: 'DeepSeek R1 1.5B (Q4_K_M)',
    family: 'deepseek',
    parameterBillions: 1.5,
    sizeTier: 'tiny',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 1.8,
    ramRecommendedGB: 3.0,
    diskSizeGB: 1.1,
    ollamaTag: 'deepseek-r1:1.5b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-1.5B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf',
    ggufFileSize: 1120000000,
    description: 'DeepSeek\'s ultra-lightweight reasoning model. Outputs chain-of-thought `<think>` tags.',
    highlights: ['Native chain-of-thought reasoning', 'Runs on low-end hardware', 'Impressive math and logic for size']
  },
  {
    id: 'deepseek-r1:7b-q4',
    name: 'DeepSeek R1 7B (Q4_K_M)',
    family: 'deepseek',
    parameterBillions: 7.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 5.0,
    ramRecommendedGB: 8.0,
    diskSizeGB: 4.7,
    ollamaTag: 'deepseek-r1:7b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf',
    ggufFileSize: 4680000000,
    description: 'DeepSeek\'s distilled 7B model. Strikingly strong reasoning, math, and coding abilities.',
    highlights: ['Best value-to-performance reasoning', 'Detailed step-by-step thinking', 'Great for 8GB/16GB RAM machines']
  },
  {
    id: 'deepseek-r1:8b-q4',
    name: 'DeepSeek R1 8B (Llama-based)',
    family: 'deepseek',
    parameterBillions: 8.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 5.5,
    ramRecommendedGB: 8.0,
    diskSizeGB: 4.7,
    ollamaTag: 'deepseek-r1:8b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Llama-8B-GGUF/resolve/main/DeepSeek-R1-Distill-Llama-8B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Llama-8B-Q4_K_M.gguf',
    ggufFileSize: 4920000000,
    description: 'DeepSeek\'s reasoning model distilled into the Llama 3.1 8B architecture.',
    highlights: ['Llama-based fine-tune', 'Excellent logical consistency', 'Runs well on 16GB unified memory']
  },
  {
    id: 'deepseek-r1:14b-q4',
    name: 'DeepSeek R1 14B (Q4_K_M)',
    family: 'deepseek',
    parameterBillions: 14.0,
    sizeTier: 'medium',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 9.5,
    ramRecommendedGB: 16.0,
    diskSizeGB: 9.0,
    ollamaTag: 'deepseek-r1:14b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-14B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf',
    ggufFileSize: 9000000000,
    description: 'DeepSeek\'s distilled 14B Qwen-based model. Excellent for intermediate complex problem-solving.',
    highlights: ['Strong developer companion', 'Highly detailed explanations', 'Needs 16GB+ RAM']
  },
  {
    id: 'deepseek-r1:32b-q4',
    name: 'DeepSeek R1 32B (Q4_K_M)',
    family: 'deepseek',
    parameterBillions: 32.0,
    sizeTier: 'large',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 20.0,
    ramRecommendedGB: 24.0,
    diskSizeGB: 20.0,
    ollamaTag: 'deepseek-r1:32b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-32B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf',
    ggufFileSize: 20000000000,
    description: 'Distilled 32B reasoning model. Near frontier-level math and coding capabilities.',
    highlights: ['Frontier-like math/coding', 'Deep logical synthesis', 'Requires 24GB-32GB RAM/VRAM']
  },
  {
    id: 'deepseek-r1:70b-q4',
    name: 'DeepSeek R1 70B (Q4_K_M)',
    family: 'deepseek',
    parameterBillions: 70.0,
    sizeTier: 'xl',
    quantization: 'Q4_K_M',
    useCases: ['reasoning', 'chat', 'code'],
    ramRequiredGB: 43.0,
    ramRecommendedGB: 48.0,
    diskSizeGB: 42.0,
    ollamaTag: 'deepseek-r1:70b',
    ggufUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Llama-70B-GGUF/resolve/main/DeepSeek-R1-Distill-Llama-70B-Q4_K_M.gguf',
    ggufFilename: 'DeepSeek-R1-Distill-Llama-70B-Q4_K_M.gguf',
    ggufFileSize: 42500000000,
    description: 'DeepSeek R1 distilled into Llama 70B. Superb reasoning capacity matching top closed models.',
    highlights: ['Exceptional performance', 'Full complex analysis', 'Requires high-end Mac Studio or multi-GPU PC']
  },

  // Gemma family
  {
    id: 'gemma2:2b-q4',
    name: 'Gemma 2 2B (Q4_K_M)',
    family: 'gemma',
    parameterBillions: 2.6,
    sizeTier: 'tiny',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'creative'],
    ramRequiredGB: 2.2,
    ramRecommendedGB: 3.0,
    diskSizeGB: 1.6,
    ollamaTag: 'gemma2:2b',
    description: 'Google\'s compact Gemma 2 model. Highly optimized for its small size.',
    highlights: ['Very fast', 'Polished conversational tone', 'Great for mobile and lightweight computers']
  },
  {
    id: 'gemma2:9b-q4',
    name: 'Gemma 2 9B (Q4_K_M)',
    family: 'gemma',
    parameterBillions: 9.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning'],
    ramRequiredGB: 6.2,
    ramRecommendedGB: 9.0,
    diskSizeGB: 5.5,
    ollamaTag: 'gemma2',
    description: 'Google\'s 9B parameter model. Outperforms many larger models on reasoning benchmarks.',
    highlights: ['Excellent general reasoning', 'Clean coding assistant', 'Requires 12GB+ RAM for peak performance']
  },
  {
    id: 'gemma2:27b-q4',
    name: 'Gemma 2 27B (Q4_K_M)',
    family: 'gemma',
    parameterBillions: 27.0,
    sizeTier: 'large',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning', 'creative'],
    ramRequiredGB: 18.0,
    ramRecommendedGB: 24.0,
    diskSizeGB: 16.0,
    ollamaTag: 'gemma2:27b',
    description: 'Google\'s powerful 27B model. Incredible text generation and structural understanding.',
    highlights: ['Frontier-level language skills', 'Excellent markdown styling', 'Needs 24GB-32GB RAM']
  },

  // Qwen Family
  {
    id: 'qwen2.5:0.5b-q4',
    name: 'Qwen 2.5 0.5B (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 0.5,
    sizeTier: 'tiny',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'embedding'],
    ramRequiredGB: 0.8,
    ramRecommendedGB: 1.2,
    diskSizeGB: 0.4,
    ollamaTag: 'qwen2.5:0.5b',
    description: 'Super-tiny model by Alibaba, suitable for very low resource microcontrollers and servers.',
    highlights: ['Lightning fast', 'Extremely low memory', 'Excellent multilingual base']
  },
  {
    id: 'qwen2.5:7b-q4',
    name: 'Qwen 2.5 7B (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 7.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'creative'],
    ramRequiredGB: 5.0,
    ramRecommendedGB: 8.0,
    diskSizeGB: 4.7,
    ollamaTag: 'qwen2.5',
    description: 'Alibaba\'s standard 7B model. Famous for its excellent coding and multilingual skills.',
    highlights: ['Great multilingual support', 'Strong tool-calling/JSON', 'Runs beautifully on 8GB/16GB systems']
  },
  {
    id: 'qwen2.5-coder:7b-q4',
    name: 'Qwen 2.5 Coder 7B (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 7.0,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['code'],
    ramRequiredGB: 5.0,
    ramRecommendedGB: 8.0,
    diskSizeGB: 4.7,
    ollamaTag: 'qwen2.5-coder',
    description: 'Specialized code-generation model from Alibaba. Outperforms GPT-4o-mini on coding benchmarks.',
    highlights: ['Superior code completion', 'Deep syntax understanding', 'Active developer community']
  },
  {
    id: 'qwen2.5-coder:14b-q4',
    name: 'Qwen 2.5 Coder 14B (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 14.0,
    sizeTier: 'medium',
    quantization: 'Q4_K_M',
    useCases: ['code', 'reasoning'],
    ramRequiredGB: 9.5,
    ramRecommendedGB: 16.0,
    diskSizeGB: 9.0,
    ollamaTag: 'qwen2.5-coder:14b',
    description: 'Alibaba\'s mid-sized coding model. Perfect balance between speed and advanced code design.',
    highlights: ['Complex software architecture design', 'Wide language coverage', 'Needs 16GB+ RAM']
  },
  {
    id: 'qwen2.5:32b-q4',
    name: 'Qwen 2.5 32B (Q4_K_M)',
    family: 'qwen',
    parameterBillions: 32.0,
    sizeTier: 'large',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning', 'creative'],
    ramRequiredGB: 20.0,
    ramRecommendedGB: 24.0,
    diskSizeGB: 19.0,
    ollamaTag: 'qwen2.5:32b',
    description: 'Large-scale Qwen model. Excellent reasoning, instruction following, and multilingual coding.',
    highlights: ['Superb multi-step logic', 'Accurate translations', 'Needs 24GB-32GB system memory']
  },

  // Mistral & Mixtral MoE
  {
    id: 'mistral:7b-q4',
    name: 'Mistral 7B (Q4_K_M)',
    family: 'mistral',
    parameterBillions: 7.2,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'creative'],
    ramRequiredGB: 5.0,
    ramRecommendedGB: 8.0,
    diskSizeGB: 4.1,
    ollamaTag: 'mistral',
    description: 'The classic 7B model by Mistral AI. Highly customizable and runs well everywhere.',
    highlights: ['Fast inference', 'Good general knowledge', 'Solid baseline 7B model']
  },
  {
    id: 'mixtral:8x7b-q4',
    name: 'Mixtral 8x7B MoE (Q4_K_M)',
    family: 'mistral',
    parameterBillions: 46.7,
    sizeTier: 'large',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning'],
    ramRequiredGB: 28.0,
    ramRecommendedGB: 32.0,
    diskSizeGB: 26.0,
    ollamaTag: 'mixtral',
    description: 'High-quality Mixture of Experts model. Employs 8 sub-networks, routing tokens dynamically.',
    highlights: ['Fast execution for its capacity', '32k context', 'Needs 32GB+ RAM/VRAM']
  },

  // Phi family
  {
    id: 'phi3:3.8b-q4',
    name: 'Phi-3 3.8B (Q4_K_M)',
    family: 'phi',
    parameterBillions: 3.8,
    sizeTier: 'small',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'reasoning'],
    ramRequiredGB: 3.0,
    ramRecommendedGB: 4.5,
    diskSizeGB: 2.2,
    ollamaTag: 'phi3',
    description: 'Microsoft\'s compact Phi-3 model. Trained on high-quality web data and textbooks.',
    highlights: ['Excellent logic for small size', 'Microsoft research-backed', 'Very light hardware requirements']
  },
  {
    id: 'phi4:14b-q4',
    name: 'Phi-4 14B (Q4_K_M)',
    family: 'phi',
    parameterBillions: 14.0,
    sizeTier: 'medium',
    quantization: 'Q4_K_M',
    useCases: ['chat', 'code', 'reasoning'],
    ramRequiredGB: 9.5,
    ramRecommendedGB: 16.0,
    diskSizeGB: 9.1,
    ollamaTag: 'phi4',
    description: 'Microsoft\'s state-of-the-art 14B parameter model. Highly competitive reasoning capabilities.',
    highlights: ['Frontier-level logical reasoning', 'Great scientific/math ability', 'Requires 16GB+ memory']
  },

  // Vision capabilities
  {
    id: 'llama3.2-vision:11b-q4',
    name: 'Llama 3.2 Vision 11B (Q4_K_M)',
    family: 'llama',
    parameterBillions: 11.0,
    sizeTier: 'medium',
    quantization: 'Q4_K_M',
    useCases: ['vision', 'chat'],
    ramRequiredGB: 8.5,
    ramRecommendedGB: 12.0,
    diskSizeGB: 7.9,
    ollamaTag: 'llama3.2-vision',
    description: 'Meta\'s multimodal model. Can understand and describe image contents along with text.',
    highlights: ['Handles chart/graph reading', 'Image descriptions', 'Requires 16GB RAM for smooth visual processing']
  },

  // Embedding model
  {
    id: 'nomic-embed-text:latest',
    name: 'Nomic Embed Text (FP16)',
    family: 'nomic',
    parameterBillions: 0.137,
    sizeTier: 'tiny',
    quantization: 'FP16',
    useCases: ['embedding'],
    ramRequiredGB: 0.5,
    ramRecommendedGB: 1.0,
    diskSizeGB: 0.274,
    ollamaTag: 'nomic-embed-text',
    description: 'High-performance text embedding model with large token context. Crucial for RAG pipelines.',
    highlights: ['8192 context length', 'Extremely lightweight', 'Used for local document search and vector indexing']
  }
]
